apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: storage-local-pvc
  # label:
  #   object: storage-pvc
  #   appointment: configs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""